#!/usr/bin/python

import click
import sys

from ops import build


class BuildCommands(object):
    ''' Commands for building MOSS switch config files '''

    @click.group(help='Commands for building config files for MOSS switches')
    def build():
        pass


    @click.command(help='Generate config files for entire CLOS network')
    @click.option('--port-count', type=click.Choice(['32', '48']))
    @click.option('--prefix', default = '', help='/64 routing prefix to be used for CLOS')
    @click.option('--tor-count', default = 0, help='Total number of TORs in datacenter')
    def clos(port_count, prefix, tor_count):
        if not prefix:
            print 'A prefix must be given!'
            sys.exit()

        build.generate_clos(port_count, prefix, tor_count)


    @click.command(help='Generate config file for individual switch')
    def switch():
        pass


    build.add_command(clos)
    build.add_command(switch)


@click.group()
def main():
    '''
    \033[1;32mmoss\033[0m is a CLI tool for managing \033[1;32mMOSS\033[0m switches
    '''


main.add_command(BuildCommands().build, name='build-config')



if __name__ == "__main__":
    main()